In [5]:
import pandas as pd
import numpy as np

In [6]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}

In [77]:
df = pd.DataFrame(data)

In [10]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [58]:
data_tuples = [
    ("Alice", 25, "New York"),
    ("Bob", 30, "Los Angeles"),
    ("Charlie", 35, "Chicago"),
    ("David", 40, "Houston"),
    ("Eve", 45, "Phoenix"),
    ("Frank", 50, "Philadelphia"),
    ("Grace", 55, "San Antonio"),
    ("Heidi", 60, "San Diego"),
    ("Ivan", 65, "Dallas"),
    ("Judy", 70, "San Jose"),
    ("Ken", 75, "Austin"),
    ("Leo",None, "Jacksonville"),
    ("Mallory", 85, "Fort Worth"),
    ("Nina", 90,None),
    (None, 95, "Charlotte")
]

df_tuples = pd.DataFrame(data=data_tuples,  columns=["Name","Age", "City"])
df_tuples

       Name   Age          City
0     Alice  25.0      New York
1       Bob  30.0   Los Angeles
2   Charlie  35.0       Chicago
3     David  40.0       Houston
4       Eve  45.0       Phoenix
5     Frank  50.0  Philadelphia
6     Grace  55.0   San Antonio
7     Heidi  60.0     San Diego
8      Ivan  65.0        Dallas
9      Judy  70.0      San Jose
10      Ken  75.0        Austin
11      Leo   NaN  Jacksonville
12  Mallory  85.0    Fort Worth
13     Nina  90.0          None
14     None  95.0     Charlotte

In [60]:
# adding a new column
df_tuples["Age_After_5_Years"] = df_tuples["Age"] + 5

In [61]:
# filtering rows based on a condition
df_filtered = df_tuples[df_tuples["Age"] > 30]
# calculating the mean age
mean_age = df_tuples["Age"].mean()
print("Mean Age:", mean_age)

# find max age record
max_age_record = df_tuples[df_tuples["Age"] == df_tuples["Age"].max()].values[0]
max_age_record

# grouping by city and calculating the average age
grouped = df_tuples.groupby("City")["Age"].mean()
nummber_of_persons_in_city = df_tuples.groupby("Name").count()
print(grouped)
print(nummber_of_persons_in_city)
# sorting by age
sorted_df = df_tuples.sort_values(by="Age", ascending=False)
print(sorted_df)
df_tuples.to_csv("people.csv", index=True)

Mean Age: 58.57142857142857
City
Austin          75.0
Charlotte       95.0
Chicago         35.0
Dallas          65.0
Fort Worth      85.0
Houston         40.0
Jacksonville     NaN
Los Angeles     30.0
New York        25.0
Philadelphia    50.0
Phoenix         45.0
San Antonio     55.0
San Diego       60.0
San Jose        70.0
Name: Age, dtype: float64
         Age  City  Age_After_5_Years
Name
Alice      1     1                  1
Bob        1     1                  1
Charlie    1     1                  1
David      1     1                  1
Eve        1     1                  1
Frank      1     1                  1
Grace      1     1                  1
Heidi      1     1                  1
Ivan       1     1                  1
Judy       1     1                  1
Ken        1     1                  1
Leo        0     1                  0
Mallory    1     1                  1
Nina       1     0                  1
       Name   Age          City  Age_After_5_Years
14     None  95.0     Charlotte              100.0
13     Nina  90.0          None               95.0
12  Mallory  85.0    Fort Worth               90.0
10      Ken  75.0        Austin               80.0
9      Judy  70.0      San Jose               75.0
8      Ivan  65.0        Dallas               70.0
7     Heidi  60.0     San Diego               65.0
6     Grace  55.0   San Antonio               60.0
5     Frank  50.0  Philadelphia               55.0
4       Eve  45.0       Phoenix               50.0
3     David  40.0       Houston               45.0
2   Charlie  35.0       Chicago               40.0
1       Bob  30.0   Los Angeles               35.0
0     Alice  25.0      New York               30.0
11      Leo   NaN  Jacksonville                NaN

In [69]:
df_filtered

       Name   Age          City  Age_After_5_Years
2   Charlie  35.0       Chicago               40.0
3     David  40.0       Houston               45.0
4       Eve  45.0       Phoenix               50.0
5     Frank  50.0  Philadelphia               55.0
6     Grace  55.0   San Antonio               60.0
7     Heidi  60.0     San Diego               65.0
8      Ivan  65.0        Dallas               70.0
9      Judy  70.0      San Jose               75.0
10      Ken  75.0        Austin               80.0
12  Mallory  85.0    Fort Worth               90.0
13     Nina  90.0          None               95.0
14     None  95.0     Charlotte              100.0

In [70]:
# filling missing values with a specific value
df_filled = df_tuples.fillna({"Age": df_tuples["Age"].mean(), "City": "Mumbai", "Name": "Heros"})
# checking for missing values
# missing_values = df_tuples.isnull().sum()

In [71]:
df_filled
# missing_values

       Name        Age          City  Age_After_5_Years
0     Alice  25.000000      New York               30.0
1       Bob  30.000000   Los Angeles               35.0
2   Charlie  35.000000       Chicago               40.0
3     David  40.000000       Houston               45.0
4       Eve  45.000000       Phoenix               50.0
5     Frank  50.000000  Philadelphia               55.0
6     Grace  55.000000   San Antonio               60.0
7     Heidi  60.000000     San Diego               65.0
8      Ivan  65.000000        Dallas               70.0
9      Judy  70.000000      San Jose               75.0
10      Ken  75.000000        Austin               80.0
11      Leo  58.571429  Jacksonville                NaN
12  Mallory  85.000000    Fort Worth               90.0
13     Nina  90.000000        Mumbai               95.0
14    Heros  95.000000     Charlotte              100.0

In [75]:
# renaming columns
df_tuples.rename(columns={"Age_After_5_Years": "Vadapav"}, inplace=True)
df_tuples
# dropping rows with missing values
# df_dropped = df_tuples.dropna()
# applying a function to a column
df_tuples["Age Squared"] = df_tuples["Age"].apply(lambda x: x**2)
# applying a function to the entire dataframe
df_tuples["Age Category"] = df_tuples["Age"].apply(lambda x: "Young" if x < 30 else "Middle-aged" if x < 60 else "Senior")

In [76]:
df_tuples

       Name   Age          City  Vadapav  Age Squared Age Category
0     Alice  25.0      New York     30.0        625.0        Young
1       Bob  30.0   Los Angeles     35.0        900.0  Middle-aged
2   Charlie  35.0       Chicago     40.0       1225.0  Middle-aged
3     David  40.0       Houston     45.0       1600.0  Middle-aged
4       Eve  45.0       Phoenix     50.0       2025.0  Middle-aged
5     Frank  50.0  Philadelphia     55.0       2500.0  Middle-aged
6     Grace  55.0   San Antonio     60.0       3025.0  Middle-aged
7     Heidi  60.0     San Diego     65.0       3600.0       Senior
8      Ivan  65.0        Dallas     70.0       4225.0       Senior
9      Judy  70.0      San Jose     75.0       4900.0       Senior
10      Ken  75.0        Austin     80.0       5625.0       Senior
11      Leo   NaN  Jacksonville      NaN          NaN       Senior
12  Mallory  85.0    Fort Worth     90.0       7225.0       Senior
13     Nina  90.0          None     95.0       8100.0       Senior
14     None  95.0     Charlotte    100.0       9025.0       Senior

In [89]:
# df_merged = pd.merge(df, df_tuples, on=["Name", "Age", "City"], how="left")
# concatenating two dataframes
df_concatenated = pd.concat([df, df_tuples], ignore_index=True, sort=True)

In [101]:
# pivoting a dataframe
# df_pivoted = df_tuples.pivot(index="Name", columns="City", values="Age")
# df_pivoted
# melting a dataframe
# df_melted = df_tuples.melt(id_vars=["Name"], value_vars=["Age", "City"], var_name="Variable", value_name="Value")
# df_melted

# df_tuples.explode("City").reset_index(drop=True)
df_tuples.empty

False

In [102]:
df_tuples["City"]

0         New York
1      Los Angeles
2          Chicago
3          Houston
4          Phoenix
5     Philadelphia
6      San Antonio
7        San Diego
8           Dallas
9         San Jose
10          Austin
11    Jacksonville
12      Fort Worth
13            None
14       Charlotte
Name: City, dtype: object