In [1]:
import pandas as pd
ages = pd.Series([22, 35, 58], name="Age")

In [2]:
ages

0    22
1    35
2    58
Name: Age, dtype: int64

In [ ]:
#constructing dataframe from dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}   

df = pd.DataFrame(data)

In [4]:
# constructing dataframe from list of dictionaries
data_list = [
    {"Name": "Alice", "Age": 25, "City": "New York"},
    {"Name": "Bob", "Age": 30, "City": "Los Angeles"},
    {"Name": "Charlie", "Age": 35, "City": "Chicago"},
    {"Name": "David", "Age": 40, "City": "Houston"},
    {"Name": "Eve", "Age": 45, "City": "Phoenix"},
    {"Name": "Frank", "Age": 50, "City": "Philadelphia"},
    {"Name": "Grace", "Age": 55, "City": "San Antonio"},
    {"Name": "Heidi", "Age": 60, "City": "San Diego"},
    {"Name": "Ivan", "Age": 65, "City": "Dallas"},
    {"Name": "Judy", "Age": 70, "City": "San Jose"}
]
df_list = pd.DataFrame(data_list)

In [ ]:
df
# df_list

In [6]:
# creating dataframe from list of tuples
data_tuples = [
    ("Alice", 25, "New York"),
    ("Bob", 30, "Los Angeles"),
    ("Charlie", 35, "Chicago"),
    ("David", 40, "Houston"),
    ("Eve", 45, "Phoenix"),
    ("Frank", 50, "Philadelphia"),
    ("Grace", 55, "San Antonio"),
    ("Heidi", 60, "San Diego"),
    ("Ivan", 65, "Dallas"),
    ("Judy", 70, "San Jose")
]
df_tuples = pd.DataFrame(data_tuples, columns=["Name", "Age", "City"])

In [ ]:
# search for a specific name
df_tuples[df_tuples["Name"] == "Alice"]

In [ ]:
#manipulating dataframes
# adding a new column
df_tuples["Age in 5 Years"] = df_tuples["Age"] + 5
# filtering rows based on a condition
df_filtered = df_tuples[df_tuples["Age"] > 30]
# calculating the mean age
mean_age = df_tuples["Age"].mean()
# grouping by city and calculating the average age
grouped = df_tuples.groupby("City")["Age"].mean()
# sorting by age
sorted_df = df_tuples.sort_values(by="Age", ascending=True)
# saving to a CSV file
df_tuples.to_csv("people.csv", index=False)
# loading from a CSV file
df_loaded = pd.read_csv("people.csv")
# displaying the first few rows of the dataframe
df_loaded.head()
# displaying the last few rows of the dataframe
df_loaded.tail()
# getting summary statistics
summary_stats = df_tuples.describe()
# getting the data types of each column
data_types = df_tuples.dtypes
# checking for missing values
missing_values = df_tuples.isnull().sum()
# renaming columns
df_tuples.rename(columns={"Age in 5 Years": "Age in Five Years"}, inplace=True)
# dropping a column
df_tuples.drop(columns=["Age in Five Years"], inplace=True)
# dropping rows with missing values
df_dropped = df_tuples.dropna()
# filling missing values with a specific value
df_filled = df_tuples.fillna(0)
# applying a function to a column
df_tuples["Age Squared"] = df_tuples["Age"].apply(lambda x: x**2)
# applying a function to multiple columns
df_tuples["Name Length"] = df_tuples["Name"].apply(len)
# applying a function to the entire dataframe
df_tuples["Age Category"] = df_tuples["Age"].apply(lambda x: "Young" if x < 30 else "Middle-aged" if x < 60 else "Senior")
# merging two dataframes
df_merged = pd.merge(df, df_tuples, on=["Name", "Age", "City"], how="inner")
# concatenating two dataframes
df_concatenated = pd.concat([df, df_tuples], ignore_index=True)
# pivoting a dataframe
df_pivoted = df_tuples.pivot(index="Name", columns="City", values="Age")
# melting a dataframe
df_melted = df_tuples.melt(id_vars=["Name"], value_vars=["Age", "City"], var_name="Variable", value_name="Value")

In [ ]:
## pivoting a dataframe
# DataFrame pivoting in pandas means reshaping data by turning 
# unique values from one column into multiple columns, reorganizing the 
# table structure.
df_pivoted = df_tuples.pivot(index="Name", columns="City", values="Age")

In [ ]:
df_pivoted

In [26]:
# melting a dataframe
# Melting in pandas means transforming columns into rows — converting
# a wide format DataFrame into a long format.It is the opposite of pivoting.
df_melted = df_tuples.melt(id_vars=["Name"], value_vars=["Age", "City"], var_name="Variable", value_name="Value")

In [ ]:
df_melted

In [ ]:
# handling missing data
# creating a dataframe with missing values
data_with_missing = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, None, 35, 40],
    "City": ["New York", "Los Angeles", None, "Houston"]
}
df_with_missing = pd.DataFrame(data_with_missing)
df_with_missing
# handling missing data by dropping rows with missing values
df_dropped = df_with_missing.dropna()
df_dropped
# handling missing data by filling missing values with a specific value
df_filled = df_with_missing.fillna({"Age": df_with_missing["Age"].mean(), "City": "Unknown"})
df_filled

In [ ]:
# SQL-like operations
# creating a dataframe for SQL-like operations
data_sql = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"]
}
df_sql = pd.DataFrame(data_sql)
# selecting specific columns
selected_columns = df_sql[["Name", "Age"]]
selected_columns

# filtering rows based on a condition
filtered_rows = df_sql[df_sql["Age"] > 30]
filtered_rows
# grouping by city and calculating the average age
grouped = df_sql.groupby("City")["Age"].mean()
grouped
# sorting by age
sorted_df = df_sql.sort_values(by="Age", ascending=True)
sorted_df

In [4]:
# downloading a CSV file from a URL and loading it into a dataframe
url = (
    "https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/tips.csv"
)

In [5]:
tips_df = pd.read_csv(url)
# tips_df.head()
# tips_df.shape
# tips_df

In [7]:
print(tips_df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
## Sql Query
# SELECT total_bill, tip, smoker, time FROM tips;

# Equivalent pandas code:
tips_df[["total_bill", "tip", "smoker", "time"]]    

# In SQL, you can add a calculated column:
# SELECT *, tip/total_bill as tip_rate FROM tips;

# Equivalent pandas code:
tips_df["tip_rate"] = tips_df["tip"] / tips_df["total_bill"]

tips_df[["total_bill", "tip", "smoker", "time", "tip_rate"]]

# SELECT * FROM tips WHERE time = 'Dinner';
# equivalent pandas code:
tips_df[tips_df["time"] == "Dinner"]

# SELECT * FROM tips WHERE time = 'Dinner' AND tip > 5.00;
# equivalent pandas code:
tips_df[(tips_df["time"] == "Dinner") & (tips_df["tip"] > 5.00)]

#

In [8]:
# SELECT sex, count(*) FROM tips GROUP BY sex;
# /*
# Female     87
# Male      157
# */
tips_df.groupby("sex").size()
tips_df.groupby("sex").count()
tips_df.groupby("sex")["total_bill"].count()

sex
Female     87
Male      157
Name: total_bill, dtype: int64

In [9]:
# SELECT day, AVG(tip), COUNT(*) FROM tips GROUP BY day;
# /*
# Fri   2.734737   19
# Sat   2.993103   87
# Sun   3.255132   76
# Thu  2.771452   62
# */
tips_df.groupby("day").agg({"tip": "mean", "day": "size"})

           tip  day
day
Fri   2.734737   19
Sat   2.993103   87
Sun   3.255132   76
Thur  2.771452   62

In [19]:
## consider a more complex SQL query:
import numpy as np
df1 = pd.DataFrame({"key": ["A", "B", "C", "D"], "value": np.random.randn(4)})
df2 = pd.DataFrame({"key": ["B", "D", "D", "E"], "value": np.random.randn(4)})

# # inner join to merge df1 and df2 on the "key" column
df_merger1=pd.merge(df1, df2, on="key")

# # apply a left join to merge df1 and df2 on the "key" column
#df_merged = pd.merge(df1, df2, on="key", how="left", suffixes=("_df1", "_df2"))
# df_merged

# # sql query for limit 
# # SELECT * FROM tips LIMIT 5;
# tips_df.head(5)
# tips_df.nlargest(10 + 5, columns="tip").tail(10)

In [16]:
df_merger1

  key   value_x   value_y
0   B -2.103404  1.689421
1   D  0.309753 -0.036762
2   D  0.309753  0.944943

In [20]:
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [25]:
tips_df["total_bill"].max()

np.float64(50.81)

In [ ]:
# find out last 2 largest total_bill
tips_df["total_bill"].nlargest(3).iloc[1:3]
# find out smallest 2 total_bill
tips_df["total_bill"].nsmallest(3).iloc[1:3]

# find out 2nd largest total_bill
tips_df["total_bill"].nlargest(2).iloc[1]

# find out 2nd smallest total_bill using negative indexing
tips_df["total_bill"].nsmallest(2).iloc[-1]

# find out 2nd smallest total_bill using negative indexing
tips_df["total_bill"].nsmallest(2).iloc[-1]

# find out last 2  smallest total_bill using negative indexing
tips_df["total_bill"].nsmallest(3).iloc[-2:]

# find out 2nd largest total_bill using negative indexing
tips_df["total_bill"].nlargest(2).iloc[-1]

212    48.33
59     48.27
Name: total_bill, dtype: float64

In [69]:
tips_df["total_bill"].nlargest(3).iloc[-1:]

59    48.27
Name: total_bill, dtype: float64

In [86]:
d1 = {"A0": ["A", "B", "C", "D"], 
      "A1": [1, 2, 3, 4], 
      "A2": [5, 6, 7, 8], 
      "A3": [9, 10, 11, 12],
      "A4": [13, 14, 15, 16]}

In [87]:
d1 = pd.DataFrame(d1)

In [88]:
d1

  A0  A1  A2  A3  A4
0  A   1   5   9  13
1  B   2   6  10  14
2  C   3   7  11  15
3  D   4   8  12  16

In [94]:
d1.iloc[-1,0:5]

A0     D
A1     4
A2     8
A3    12
A4    16
Name: 3, dtype: object